name: API Call

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '8 16 * * *'

jobs:
  CISA-KEV:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install requests

    - name: Make API call
      id: api_call
      run: |
        python3 epss_nvd.py  > FIRST_NVD.md
        cat $GITHUB_OUTPUT  # Debug: Show contents of $GITHUB_OUTPUT

    - name: Commit and Push
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add FIRST_NVD.md
        timestamp=$(date -u)
        git commit -m "Updated: ${timestamp}" || echo "No changes to commit"
        git push

